import type { Metadata } from "next";
import "./globals.css";
import CTABtn from "@compo/CTA.btn";
import localFont from "next/font/local";

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/satoshi/Satoshi-Variable.woff2',
      style: 'normal',
    },
    {
      path: '../public/fonts/satoshi/Satoshi-VariableItalic.woff2',
      style: 'italic',
    }
  ],
  variable: '--font-satoshi'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log('satoshi:: ');
  console.log(satoshi.variable);
  
  
  return (
    <html lang="en">
      <body
        className={satoshi.className}
      >

        <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">

          {children}
        </main>
        <footer>
          <video width="320" height="240" controls preload="none">
            <source src="/assets/footer_bg_video.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <div>Are your ready?</div>
          <div>This could be start of something big.</div>
          <CTABtn text="Book a call" />
        </footer>
      </body>
    </html>
  );
}
