import type { Metadata } from "next";
import "./globals.css";
import CTABtn from "@compo/CTA.btn";
import localFont from "next/font/local";

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/satoshi/Satoshi-Variable.woff2',
      style: 'normal',
    },
    {
      path: '../public/fonts/satoshi/Satoshi-VariableItalic.woff2',
      style: 'italic',
    }
  ],
  variable: '--font-satoshi'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log('satoshi:: ');
  console.log(satoshi.variable);


  return (
    <html lang="en">
      <body
        className={`${satoshi.className} lg:mx-80 md:mx-60 `}
      >

        <main className=" min-h-screen w-full  items-center justify-between py-20 
        bg-black sm:items-start">

          {children}
        </main>
        <footer className="hidden md:flex flex-col bg-black">
          <video width="320" height="240" controls preload="none">
            <source src="/assets/footer_bg_video.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <div>Are your ready?</div>
          <div>This could be start of something big.</div>
          <CTABtn text="Book a call" />
        </footer>
      </body>
    </html>
  );
}
