import type { Metadata } from "next";
import "./globals.css";
import CTABtn from "@compo/CTA.btn";
import { satoshi, instru } from "./fonts"
import Nav from "@compo/Nav";
import NavTabletView from "@compo/NavTabletView";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${satoshi.variable} ${instru.variable}  `}
      >

        <main className=" min-h-screen w-full lg:px-40
          items-center justify-between   
        bg-black ">

          {children}
        </main >

      </body>
    </html>
  );
}
